### ISSUE TITLE
Compile error on Elixir 1.19: generated `@type record()` collides with new built-in `record/0`

### ISSUE THREAD

**Issue by harmoniousmoss** [aws-beam/aws-elixir#230]
## Summary

`aws` v1.0.11 fails to compile on **Elixir 1.19** because generated code defines a `@type record() :: ...`, and Elixir 1.19 now ships a built-in `record/0` type, so the typespec is rejected as a redefinition.

## Error

```
== Compilation error in file lib/aws/generated/cognito_sync.ex ==
** (Kernel.TypespecError) lib/aws/generated/cognito_sync.ex:92: type record/0 is a built-in type and it cannot be redefined
    (elixir 1.19.5) lib/kernel/typespec.ex:992: Kernel.Typespec.compile_error/2
    (stdlib 8.0) lists.erl:2470: :lists.foldl_1/3
    (elixir 1.19.5) lib/kernel/typespec.ex:230: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :aws, "mix compile" failed.
```

## Environment

- Elixir **1.19.5** (compiled with Erlang/OTP 28), running on Erlang/OTP 29
- `aws` **1.0.11** (latest)

## Reproduction

1. New project on Elixir 1.19.x
2. Add `{:aws, "~> 1.0"}`
3. `mix deps.compile aws` → fails as above

## Root cause

`lib/aws/generated/cognito_sync.ex` contains:

```elixir
@type record() :: %{(String.t() | atom()) => any()}
```

Elixir 1.19 reserves `record/0` as a built-in type, so any generated `@type record()` collides. This is **not specific to cognito_sync** — it will affect every generated module whose AWS API has a shape named `Record` (e.g. `cognito_sync`, `kinesis`, `firehose`, `dynamodb_streams`, …). It is **also present on `master`** (the generated `@type record()` is still there), so a git pin does not work around it.

## Suggested fix

In the code generator, namespace/escape generated type names that collide with Elixir built-ins (`record`, and any others), e.g. emit `record_t` / `cognito_sync_record` instead of `record`. That would regenerate all affected modules safely.

Happy to help test a fix. Thanks for the library!

**Comment by onno-vos-dev** [comment]
Hi @harmoniousmoss should be an easy fix as we already have reserved keywords support for Erlang and I'm pretty sure it's the same for Elixir. 

Will fix shortly 👍

**Comment by onno-vos-dev** [comment]
@harmoniousmoss Any chance you can give: https://github.com/aws-beam/aws-elixir/pull/231 a quick spin? I had to bump a few deps to get `mix test` to pass in the codegen but can't get a green build there without first updating aws-elixir... So either I just force merge that one despite the red build or I make 2 PRs here, one to bump deps and another to merge the updated code based on 1.19... I'd prefer to just do it all in one swoop. 

Please let me know if/when you had a chance to test that and I'll take care of the merges and releases asap 👍

**Comment by harmoniousmoss** [comment]
@onno-vos-dev Gave it a spin, builds green on Elixir 1.19

cognito_sync (the module that previously failed with type record/0 is a built-in type and it cannot be redefined) now compiles, along with the rest of the generated code. 

Also ran a quick runtime call against a live service and it worked as expected. Looks good to merge. 

Thanks for the fast turnaround! 👍

**Comment by onno-vos-dev** [comment]
Expect a release in about 3 hours (during my lunch break) 👍

**Comment by onno-vos-dev** [comment]
@harmoniousmoss Done! Released as [v1.0.12](https://hex.pm/packages/aws/1.0.12) 👍 

Thanks for the fantastically detailed issue!
